name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: log in to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build backend image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/springboot-app:latest ./backend

      - name: build frontend image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/angular-app:latest ./frontend

      - name: push backend image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/springboot-app:latest

      - name: push frontend image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/angular-app:latest

      - name: test application with docker compose
        run: |
          docker-compose up -d

    - name: check running containers
      run: |
        docker ps

    - name: test frontend backend communication
      run: |
        docker exec $(docker ps -qf "name=angular-app") curl -s http://spring-boot-app:8081/actuator/health
